from models import Property


def get_seed_properties():
    return [
        # ===== BANGALORE PROPERTIES =====
        Property(
            title="Luxury 3 BHK Apartment in Whitefield",
            description="Spacious 3 BHK apartment in a gated community with world-class amenities. Located near ITPL and major tech parks. Beautiful garden views from the balcony with modern interiors and modular kitchen.",
            city="Bangalore",
            locality="Whitefield",
            property_type="Apartment",
            listing_type="buy",
            price=12500000,
            area_sqft=1850,
            bedrooms=3,
            bathrooms=3,
            image_url="https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
            amenities="Swimming Pool,Gym,Clubhouse,Children's Play Area,24/7 Security,Power Backup,Covered Parking",
            posted_date="2026-02-15",
            furnishing="Semi-Furnished",
            parking=2,
            floor_number=8,
            total_floors=20,
        ),
        Property(
            title="Modern 2 BHK for Rent in Koramangala",
            description="Fully furnished 2 BHK apartment in the heart of Koramangala, close to restaurants, cafes, and shopping. Walking distance to metro station. Ideal for young professionals and couples.",
            city="Bangalore",
            locality="Koramangala",
            property_type="Apartment",
            listing_type="rent",
            price=35000,
            area_sqft=1200,
            bedrooms=2,
            bathrooms=2,
            image_url="https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
            amenities="Gym,Lift,Security,Power Backup,Water Supply,Gas Pipeline",
            posted_date="2026-02-20",
            furnishing="Fully Furnished",
            parking=1,
            floor_number=5,
            total_floors=12,
        ),
        Property(
            title="Premium Villa in Sarjapur Road",
            description="Stunning 4 BHK independent villa with private garden, modern architecture, and Italian marble flooring. Located in a premium gated villa community with excellent connectivity to ORR.",
            city="Bangalore",
            locality="Sarjapur Road",
            property_type="Villa",
            listing_type="buy",
            price=35000000,
            area_sqft=3500,
            bedrooms=4,
            bathrooms=4,
            image_url="https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
            amenities="Private Garden,Swimming Pool,Clubhouse,Gym,Jogging Track,Tennis Court,24/7 Security",
            posted_date="2026-02-10",
            furnishing="Semi-Furnished",
            parking=3,
            floor_number=None,
            total_floors=2,
        ),
        Property(
            title="Affordable 1 BHK in Electronic City",
            description="Compact and well-maintained 1 BHK apartment perfect for bachelors or small families. Close to Infosys and Wipro campuses with good public transport connectivity.",
            city="Bangalore",
            locality="Electronic City",
            property_type="Apartment",
            listing_type="rent",
            price=12000,
            area_sqft=650,
            bedrooms=1,
            bathrooms=1,
            image_url="https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800",
            amenities="Security,Lift,Water Supply,Power Backup",
            posted_date="2026-02-25",
            furnishing="Unfurnished",
            parking=0,
            floor_number=3,
            total_floors=8,
        ),
        Property(
            title="Spacious 3 BHK in Indiranagar",
            description="Beautifully designed 3 BHK apartment in the premium locality of Indiranagar. Walking distance to 100 Feet Road, Metro, and famous eateries. Perfect for families who love urban living.",
            city="Bangalore",
            locality="Indiranagar",
            property_type="Apartment",
            listing_type="buy",
            price=22000000,
            area_sqft=2100,
            bedrooms=3,
            bathrooms=3,
            image_url="https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800",
            amenities="Swimming Pool,Gym,Rooftop Terrace,Clubhouse,24/7 Security,Vastu Compliant,Intercom",
            posted_date="2026-01-28",
            furnishing="Fully Furnished",
            parking=2,
            floor_number=12,
            total_floors=18,
        ),
        Property(
            title="Residential Plot in Devanahalli",
            description="Prime residential plot near Bangalore International Airport. BMRDA approved layout with all basic amenities. Excellent investment opportunity with upcoming metro connectivity.",
            city="Bangalore",
            locality="Devanahalli",
            property_type="Plot",
            listing_type="buy",
            price=8500000,
            area_sqft=2400,
            bedrooms=0,
            bathrooms=0,
            image_url="https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800",
            amenities="Gated Community,Paved Roads,Drainage,Water Connection,Electricity",
            posted_date="2026-02-05",
            furnishing="Unfurnished",
            parking=0,
            floor_number=None,
            total_floors=None,
        ),
        Property(
            title="Cozy 2 BHK in HSR Layout",
            description="Well-ventilated 2 BHK apartment in a family-friendly society in HSR Layout. Close to Agara Lake, parks, and supermarkets. Ideal for families with pets.",
            city="Bangalore",
            locality="HSR Layout",
            property_type="Apartment",
            listing_type="rent",
            price=28000,
            area_sqft=1100,
            bedrooms=2,
            bathrooms=2,
            image_url="https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800",
            amenities="Gym,Children's Play Area,Lift,Security,Rainwater Harvesting,CCTV",
            posted_date="2026-02-18",
            furnishing="Semi-Furnished",
            parking=1,
            floor_number=6,
            total_floors=10,
        ),
        Property(
            title="Elegant 4 BHK Penthouse in Hebbal",
            description="Exquisite 4 BHK penthouse with panoramic city views, private terrace, and jacuzzi. Ultra-luxury living with smart home automation and designer interiors.",
            city="Bangalore",
            locality="Hebbal",
            property_type="Apartment",
            listing_type="buy",
            price=45000000,
            area_sqft=4200,
            bedrooms=4,
            bathrooms=5,
            image_url="https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
            amenities="Private Terrace,Jacuzzi,Smart Home,Home Theater,Swimming Pool,Gym,Concierge",
            posted_date="2026-01-15",
            furnishing="Fully Furnished",
            parking=3,
            floor_number=25,
            total_floors=25,
        ),
        Property(
            title="Budget Studio Apartment in Marathahalli",
            description="Well-designed studio apartment near Marathahalli Bridge. Walking distance to malls and restaurants. Fully furnished with modern appliances. Perfect for IT professionals.",
            city="Bangalore",
            locality="Marathahalli",
            property_type="Apartment",
            listing_type="rent",
            price=15000,
            area_sqft=450,
            bedrooms=1,
            bathrooms=1,
            image_url="https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800",
            amenities="Fully Furnished,Wi-Fi Ready,Security,Lift,Laundry",
            posted_date="2026-02-22",
            furnishing="Fully Furnished",
            parking=0,
            floor_number=4,
            total_floors=14,
        ),
        Property(
            title="3 BHK Villa with Garden in JP Nagar",
            description="Independent 3 BHK villa with a lush private garden and covered car park. Quiet residential area perfect for families. Close to schools, hospitals, and NICE Road.",
            city="Bangalore",
            locality="JP Nagar",
            property_type="Villa",
            listing_type="rent",
            price=55000,
            area_sqft=2800,
            bedrooms=3,
            bathrooms=3,
            image_url="https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800",
            amenities="Private Garden,Covered Parking,Servant Quarter,Rainwater Harvesting,Solar Panels",
            posted_date="2026-02-12",
            furnishing="Semi-Furnished",
            parking=2,
            floor_number=None,
            total_floors=2,
        ),

        # ===== MUMBAI PROPERTIES =====
        Property(
            title="Sea-View 3 BHK in Bandra West",
            description="Spectacular 3 BHK apartment with unobstructed sea views from every room. Located in the posh Bandra West, walking distance to Bandstand and Linking Road. Premium tower with world-class amenities.",
            city="Mumbai",
            locality="Bandra West",
            property_type="Apartment",
            listing_type="buy",
            price=55000000,
            area_sqft=1600,
            bedrooms=3,
            bathrooms=3,
            image_url="https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
            amenities="Sea View,Swimming Pool,Gym,Clubhouse,Concierge,Valet Parking,Rooftop Garden",
            posted_date="2026-02-14",
            furnishing="Semi-Furnished",
            parking=2,
            floor_number=22,
            total_floors=35,
        ),
        Property(
            title="Furnished 2 BHK in Andheri West",
            description="Ready-to-move 2 BHK apartment near Andheri Station and Metro. Ideal location for professionals with easy access to film city and corporate offices. Fully furnished with AC in all rooms.",
            city="Mumbai",
            locality="Andheri West",
            property_type="Apartment",
            listing_type="rent",
            price=45000,
            area_sqft=950,
            bedrooms=2,
            bathrooms=2,
            image_url="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
            amenities="AC,Gym,Lift,24/7 Security,Water Supply,Power Backup,CCTV",
            posted_date="2026-02-19",
            furnishing="Fully Furnished",
            parking=1,
            floor_number=10,
            total_floors=22,
        ),
        Property(
            title="Ultra-Luxury 4 BHK in Worli",
            description="One of Mumbai's finest residences in the prestigious Worli skyline. Floor-to-ceiling windows with Arabian Sea views, Italian marble, and smart home features. Access to infinity pool and sky lounge.",
            city="Mumbai",
            locality="Worli",
            property_type="Apartment",
            listing_type="buy",
            price=120000000,
            area_sqft=3200,
            bedrooms=4,
            bathrooms=5,
            image_url="https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800",
            amenities="Infinity Pool,Sky Lounge,Smart Home,Private Lift,Gym,Spa,Wine Cellar,Concierge",
            posted_date="2026-01-20",
            furnishing="Fully Furnished",
            parking=3,
            floor_number=45,
            total_floors=60,
        ),
        Property(
            title="Affordable 1 BHK in Thane West",
            description="Well-planned 1 BHK in a reputed township in Thane. Excellent connectivity via Eastern Express Highway and upcoming metro line. Great for first-time homebuyers.",
            city="Mumbai",
            locality="Thane West",
            property_type="Apartment",
            listing_type="buy",
            price=7500000,
            area_sqft=580,
            bedrooms=1,
            bathrooms=1,
            image_url="https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800",
            amenities="Swimming Pool,Gym,Garden,Children's Play Area,Jogging Track,24/7 Security",
            posted_date="2026-02-08",
            furnishing="Unfurnished",
            parking=1,
            floor_number=7,
            total_floors=25,
        ),
        Property(
            title="Charming 2 BHK in Powai",
            description="Beautiful lakeside living in Powai with 2 BHK apartment overlooking Powai Lake. Close to IIT Bombay and Hiranandani Gardens. Modern amenities and serene environment.",
            city="Mumbai",
            locality="Powai",
            property_type="Apartment",
            listing_type="rent",
            price=38000,
            area_sqft=1050,
            bedrooms=2,
            bathrooms=2,
            image_url="https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800",
            amenities="Lake View,Swimming Pool,Gym,Clubhouse,Jogging Track,Security,Tennis Court",
            posted_date="2026-02-21",
            furnishing="Semi-Furnished",
            parking=1,
            floor_number=14,
            total_floors=28,
        ),
        Property(
            title="Spacious Row House in Navi Mumbai",
            description="Beautiful 3 BHK row house in Kharghar with private terrace and covered parking. Part of a well-maintained township with parks and schools. Close to Pandavkada Falls.",
            city="Mumbai",
            locality="Navi Mumbai - Kharghar",
            property_type="Villa",
            listing_type="buy",
            price=18000000,
            area_sqft=2200,
            bedrooms=3,
            bathrooms=3,
            image_url="https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800",
            amenities="Private Terrace,Covered Parking,Garden,Clubhouse,Swimming Pool,Gym",
            posted_date="2026-02-01",
            furnishing="Semi-Furnished",
            parking=2,
            floor_number=None,
            total_floors=3,
        ),
        Property(
            title="Premium Studio in Lower Parel",
            description="Smart studio apartment in Mumbai's business district. Walking distance to Phoenix Mills and corporate offices. Floor-to-ceiling windows with city views. Perfect for working professionals.",
            city="Mumbai",
            locality="Lower Parel",
            property_type="Apartment",
            listing_type="rent",
            price=32000,
            area_sqft=520,
            bedrooms=1,
            bathrooms=1,
            image_url="https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800",
            amenities="Gym,Rooftop Pool,Business Center,Concierge,24/7 Security,Laundry Service",
            posted_date="2026-02-23",
            furnishing="Fully Furnished",
            parking=1,
            floor_number=18,
            total_floors=40,
        ),
        Property(
            title="3 BHK in Goregaon East",
            description="Spacious 3 BHK in a premium complex in Goregaon East. Near Film City and Western Express Highway. Vastu-compliant with excellent ventilation and natural light.",
            city="Mumbai",
            locality="Goregaon East",
            property_type="Apartment",
            listing_type="buy",
            price=19500000,
            area_sqft=1400,
            bedrooms=3,
            bathrooms=2,
            image_url="https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800",
            amenities="Swimming Pool,Gym,Indoor Games,Garden,Clubhouse,Power Backup,Vastu Compliant",
            posted_date="2026-02-06",
            furnishing="Semi-Furnished",
            parking=1,
            floor_number=15,
            total_floors=30,
        ),
        Property(
            title="Compact 1 BHK for Rent in Malad West",
            description="Well-maintained 1 BHK apartment near Malad Station. Ideal location with access to Inorbit Mall, Link Road, and major bus routes. Suitable for small families or couples.",
            city="Mumbai",
            locality="Malad West",
            property_type="Apartment",
            listing_type="rent",
            price=22000,
            area_sqft=550,
            bedrooms=1,
            bathrooms=1,
            image_url="https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800",
            amenities="Lift,Security,Water Supply,Power Backup,CCTV",
            posted_date="2026-02-26",
            furnishing="Semi-Furnished",
            parking=0,
            floor_number=4,
            total_floors=7,
        ),
        Property(
            title="Residential Plot in Panvel",
            description="CIDCO-approved residential plot in Panvel near upcoming Navi Mumbai International Airport. Excellent investment with projected appreciation. All basic infrastructure in place.",
            city="Mumbai",
            locality="Panvel",
            property_type="Plot",
            listing_type="buy",
            price=6500000,
            area_sqft=1800,
            bedrooms=0,
            bathrooms=0,
            image_url="https://images.unsplash.com/photo-1628624747186-a941c476b7ef?w=800",
            amenities="Paved Roads,Drainage,Water Connection,Electricity,Boundary Wall,Gated Community",
            posted_date="2026-02-03",
            furnishing="Unfurnished",
            parking=0,
            floor_number=None,
            total_floors=None,
        ),
    ]
